(ns blessing.human-id)

(def a ["memorizable"
        "honorable"
        "great"
        "slimy"
        "wise"
        "golden"
        "white"
        "eternal"
        "mighty"
        "infinite"
        "blessed"  
        "loving"
        "graceful"
        "magnificent"
        "powerful"
        "holy"
        "pure"
        "sacred"
        "divine"
        "heavenly"
        "angelic"
        "saintly"
        "godly"
        "spiritual"
        "celestial"
        "eternal"
        "immortal"
        "divine"
        "sacred"
        "blessed"
        "holy"
        "pure"
        "saintly"
        "godly"
        "spiritual"
        "celestial"
        "eternal"
        "immortal"
        "sacred"
        "blessed"
        "holy"
        "spiritual"
        "celestial"
        "eternal"
        "immortal"
        ])


(def b ["wizard"
        "priest"
        "king"
        "queen"
        "angel"
        "lion"
        "gabriel"
        "paul"
        "james"
        "thomas"
        "heaven"
        "god"
        "soul"
        "earth"
        "christ"
        "saviour"
        "mind"
        "truth"
        "origin"
        "beginning"
        "light" 
        "love"
        "peace"
        "joy"
        "hope"
        "faith"
        "grace"
        "mercy"
        "compassion"
        "forgiveness"
        "redemption"
        "salvation"
        "eternity"
        "infinity"
        "divinity"
        "holiness"
        "purity"
        "saint"
        "god"
        "spirit"
        ])

(defn id []
  (let [a-idx (rand-int (count a))
        b-idx (rand-int (count b))]
    (str (a a-idx) "-" (b b-idx) "-" 
         (rand-int 10))))


(comment 
  (id)
  
;  
  )
