(ns blessing.human-id)

(def a ["angelic"
        "blessed"
        "beautiful"
        "celestial"
        "divine"
        "energetic"
        "everlasting"
        "eternal"
        "holy"
        "infinite"
        "immortal"
        "fine"
        "godly"
        "golden"
        "graceful"
        "great"
        "heavenly"
        "holy"
        "honorable"
        "loving"
        "magnificent"
        "memorizable"
        "mighty"
        "powerful"
        "pure"
        "sacred"
        "saintly"
        "sane"
        "spiritual"
        "true"
        "white"
        "wonderful"
        "wise"])


(def nouns ["angel"
            "beginning"
            "buddah"
            "christ"
            "compassion"
            "derbish"
            "divinity"
            "earth"
            "entity"
            "eternity"
            "faith"
            "forgiveness"
            "gabriel"
            "grace"
            "god"
            "heaven"
            "holiness"
            "hope"
            "infinity"
            "james"
            "joy"
            "king"
            "light"
            "love"
            "lion" 
            "magician"
            "mercy"
            "messiah"
            "monk"
            "mind"
            "origin"
            "paul"
            "peace"
            "priest"
            "queen"
            "realm"
            "redemption"
            "saint"
            "sage"
            "saviour"            
            "salvation"
            "siddatha"
            "soul"
            "spirit"
            "truth"
            "thomas"
            "universal"
            "wizard"])

(defn id []
  (let [a-idx (rand-int (count a))
        n-idx (rand-int (count nouns))]
    (str (a a-idx) "-" (nouns n-idx) "-"
         (rand-int 10))))


(comment
  (id)

;  
  )
